```plantuml
class Pessoa {
  - String nome
  - int idade
  + String getNome()
  + void setNome(String nome)
}

class Aluno {
  - String matricula
  + void matricular()
}

class Professor {
  - String siape
  + void lecionar()
}

Pessoa <|-- Aluno
Pessoa <|-- Professor

```
